from snakemake.io import expand


include: "rules/configuration.smk"
include: "rules/gimme.smk"
include: "rules/deseq2.smk"
include: "rules/ananse.smk"


rule all:
    input:
        expand("{plot_dir}/{contrasts}.{plot_type}", **config),
        rules.maelstrom.output if config.get("run_maelstrom") else [],
